version: '3.7'


networks:
  app-tier:
    driver: bridge

services:
   
  react-frontend:
    container_name: hello-world
    build:
      context: myfixedapp
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 8086:80
    environment:
      - CHOKIDAR_USEPOLLING=true    
    stdin_open: true
