# docker-compose build --parallel
# docker-compose up -d --build
version: '3.7'

networks:
  app-tier:
    driver: bridge
    
volumes:
  grails-volume:
  postgres1:
  postgres2:

services:
  s3:
    image: minio/minio
    ports:
      - 9999:9999
    volumes:
      - ./storage/minio:/data
    environment:
      - MINIO_ROOT_USER=minio-root-user
      - MINIO_ROOT_PASSWORD=minio-root-password
    command: server --address 0.0.0.0:9999 /data
    networks:
      - app-tier

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PORT_NUMBER=7489
    ports:
      - 8989:7489
    networks:
      - app-tier

  mailService:
    image: alexrudenkiy/rsoi-project:mailservice
    environment:
      - API_GATEWAY_IP=api_gateway
      - API_GATEWAY_PORT=8082
      - EMAIL_SMTP_HOST=smtp.gmail.com
      - EMAIL_SMTP_PORT=465
      - EMAIL_USERNAME=alexrudenkiy2014@gmail.com
      - EMAIL_PASSWORD=:)
    build:
      context: mailservice
      dockerfile: Dockerfile
    volumes:
      - /data/springboot-docker-compose-app
    ports:
      - 8091:8091
    networks:
      - app-tier

  reactFrontend:
      image: alexrudenkiy/rsoi-project:frontend
      build:
        context: myfixedapp
        dockerfile: Dockerfile
      volumes:
        - '.:/app'
        - '/app/node_modules'
      ports:
        - 8088:80
      environment:
        - CHOKIDAR_USEPOLLING=true
        - REACT_APP_API_GATEWAY_IP=api_gateway
        - REACT_APP_API_GATEWAY_PORT=8082

      stdin_open: true

  fileMicroservice:
    image: alexrudenkiy/rsoi-project:fileservice
    environment:
      - fileservice_port=19776
      - minio_service_endPoint=s3
      - minio_service_port=9999
    build:
      context: file-service
      dockerfile: Dockerfile
    ports:
      - 19776:19776
    networks:
      - app-tier
    depends_on:
      - s3
    restart: always

  apiGateway:
    image: alexrudenkiy/rsoi-project:gateway
    environment:
      - redis_service_endPoint=redis
      - redis_service_port=7489
      - minio_service_endPoint=s3
      - minio_service_port=9999
      - frontend_service_url=8088
      - gateway_port=9199
      - appeals_service_url=http://appeals:8080
      - users_service_url=http://users:8080
      - email_service_url=http://mailService:8091
      - file_service_internal_url=http://fileMicroservice:19776
      - file_service_external_url=http://78.132.143.84:19776
    command: bash -c 'while !</dev/tcp/appeals/8080; do sleep 1; done; while !</dev/tcp/users/8080; do sleep 1; done; node apiGateway.js'
    build:
      context: api-gateway
      dockerfile: Dockerfile
    volumes:
      - /data/springboot-docker-compose-app
    ports:
      - 9199:9199
    networks:
      - app-tier
    depends_on:
      - s3
      - users
      - appeals
    restart: always

  dbAppeals:
    image: postgres:12.3
    environment:
      - POSTGRES_DB=database_appeal
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres1:/var/lib/postgresql/data
    ports:
      - 8432:5432
    networks:
      - app-tier
    restart: always


  appeals:
    image: alexrudenkiy/rsoi-project:appeals
    expose:
      - 9990
    ports:
      - "9990:8080"
    environment:
      - DB_HOST=dbAppeals
      - DB_PORT=5432
      - DB_NAME=database_appeal
    build:
        context: appeals
        dockerfile: Dockerfile
    networks:
      - app-tier
    depends_on:
      - dbAppeals
    restart: always
      
  dbUsers:
    image: postgres:12.3
    environment:
      - POSTGRES_DB=database_user
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres2:/var/lib/postgresql/data
    ports:
      - 8433:5432
    networks:
      - app-tier      

  users:
    image: alexrudenkiy/rsoi-project:users
    expose:
      - 9991
    ports:
      - 9991:8080
    environment:
      - DB_HOST=dbUsers
      - DB_PORT=5432
      - DB_NAME=database_user
    build:
        context: users
        dockerfile: Dockerfile
    networks:
      - app-tier  
    depends_on:
      - dbUsers  