version: '3.7'


networks:
  app-tier:
    driver: bridge


services:
  reactFrontend:
    image: micro/frontend
    build:
      context: frontend
      dockerfile: ../frontend/Dockerfile
    command: npm run start
    ports:
      - 8085:3000
    volumes: 
      - ./:/frontend
      - /frontend/node_modules


    networks:
      - app-tier   
volumes:
  postgres1:
  postgres2:
