version: "2"

services:
  grails3:
    build:
      context: .
      dockerfile: Dockerfile-grails3
      args:
        GRAILS_VERSION: "3.2.7"
    image: reduardo7/docker-grails
    environment: 
      GRAILS_ENV: "docker"
      DB_HOST: postgres
      DB_NAME: database_appeal
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    volumes:
      - ./.data/gradle:/root/.gradle
      - ./.data/app/gradle:/app/gradle
      - ./.data/app/.gradle:/app/.gradle
      - ./.data/app/build:/app/build
