name: Docker Compose Actions Workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
  
    runs-on: ubuntu-latest
#     defaults:
#       run:
#         working-directory: ./mailservice
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - uses: webfactory/ssh-agent@v0.5.4
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
            
      - name: Build with Maven
        working-directory: ./mailservice
        run: mvn clean package spring-boot:repackage
        

      - name: Build the stack
        working-directory: .
        run: docker-compose -H "ssh://alex@78.132.143.84" up #docker-compose up -d
        
#       - name: Test
#         run: docker run --network container:webapp-frontend appropriate/curl -s --retry 10 --retry-connrefused http://localhost:5000/

#   dockercompose:
#     needs: build
#     runs-on: ubuntu-latest
#     steps:
